version: 0.2

env:
  variables:
    TESTING_BROWSER: "headless-chrome"

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - ls
  build:
    commands:
      - ./node_modules/cucumber/bin/cucumber.js
